### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer Aborted (core dumped)

### ISSUE THREAD

**Issue by G-200010** [h751410234/RemoteSensingTeacher#1]
I just changed the batch size from 4 to 2, everything else stayed the same. and I got this issue, could you please give me some help in how to solve this problem? (I trained the model in a 2080ti)
![2](https://github.com/h751410234/RemoteSensingTeacher/assets/172945648/4892a381-0729-4f0d-9ecf-3e73dbeccbac)

**Comment by h751410234** [comment]
This seems to be a bug in our code; I will fix this bug within a few days. However, based on our experience, setting the batch size to 2 (one image per domain) is likely to make adversarial training unsuccessful for DETR-Based networks, and this is not just with our method but appears to be the case with other methods as well. We recommend ensuring at least two images per domain.

**Comment by G-200010** [comment]
Thanks for your reply. I tried to keep the batchsize to be 4, but out of memory. Hope for your update if it is a bug. @h751410234

**Comment by h751410234** [comment]
I suspect that this error might be related to the batch size setting. I will try to replicate and fix this error in the coming days. Could you please tell me whether this error occurred right at the beginning of the training or during a specific stage of the process?

**Comment by G-200010** [comment]
It's at the beginning of the training. and I think I located the problem at line 85.
![22](https://github.com/h751410234/RemoteSensingTeacher/assets/172945648/02e2810d-7de6-40e2-aa36-f50b1a08b7a9)

**Comment by h751410234** [comment]
I changed the config file to set the batch size = 2 and then trained our model. I have successfully trained for 4 epochs without any issues. Based on the new error image you provided, it seems that the number of categories in your dataset exceeds the number set in the config (set to 4 in the xView to DOTA config file, which includes 3 categories + background). 
I suggest checking if there is an issue with the number of categories in your prepared dataset. 
751410234
***@***.***
---- Replied Message ----
***@***.***>Date6/16/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [h751410234/RemoteSensingTeacher] ConnectionResetError: [Errno 104] Connection reset by peer Aborted (core dumped) (Issue #1)
It's at the beginning of the training. and I think I located the problem at line 85.
22.png (view on web)

**Comment by h751410234** [comment]
I changed the config file to set the batch size = 2 and then trained our model. I have successfully trained for 4 epochs without any issues. Based on the new error image you provided, it seems that the number of categories in your dataset exceeds the number set in the config (set to 4 in the xView to DOTA config file, which includes 3 categories + background). 
I suggest checking if there is an issue with the number of categories in your prepared dataset.

**Comment by G-200010** [comment]
So, you mean that I need to select the three categories of Dota and  xView mentioned in the paper in data preperation stage. Did I get this right?

**Comment by h751410234** [comment]
Yes, the dataset needs preprocessing. I have specified the categories to be selected (airplanes, storage tanks, ships) and the processing method in the experimental section of the paper.

**Comment by G-200010** [comment]
Thanks for your reply. I thought it would be done in the training phase before. I will change the annotations later.

**Comment by G-200010** [comment]
And I have a small question. How much of the GPU is occupied when batchsize is equal to 2? I wonder if it will be able to  run on a 2080ti?

**Comment by h751410234** [comment]
During the training process, the usage of GPU memory fluctuates. It may be around 15GB.

**Comment by G-200010** [comment]
I got it. Thanks a lot.
