### ISSUE TITLE
The datas in this Baidu Netdisk link are deleted.

### ISSUE THREAD

**Issue by JiajingZhuang** [h751410234/RemoteSensingTeacher#10]
The datasets in this Baidu Netdisk link are deleted. Could you please send me the processed xView and DOTA1.0 datasets. I'd appreciate it if you could do this.

**Comment by h751410234** [comment]
用这个https://pan.baidu.com/s/1G37LVIZVjt5UBBBV7LsjWw?pwd=6el9
