### ISSUE TITLE
sh ~/make.sh:The detected CUDA version (9.2) mismatches the version that was used to compile PyTorch (11.7)

### ISSUE THREAD

**Issue by yyygh007** [h751410234/RemoteSensingTeacher#11]
![image](https://github.com/user-attachments/assets/cd8f4fb4-879d-46e4-af5a-9fa6ccbfb5c3)

**Comment by h751410234** [comment]
这个是环境没配置好。看起来是编译准备用的cuda版本和实际用的不匹配。

**Comment by yyygh007** [comment]
> 这个是环境没配置好。看起来是编译准备用的cuda版本和实际用的不匹配。

是因为MultiScaleDeformableAttention这个模块的编译是需要限定cuda版本为9.2嘛？参考“Please refer to the instructions [here](https://github.com/fundamentalvision/Deformable-DETR/#installation). We leave our system information for reference.”这个项目中时，他指示是要下载cudatoolkit==9.2；不匹配后，我把本地的cuda==9.2删除之后，会报出找不到cuda9.2文件的报错

**Comment by h751410234** [comment]
cuda版本不用限定在9.2。我觉得直接修改报错的位置，让cuda_str_version和torchversion.cuda一样应该就能编译过去。
