### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by G-200010** [h751410234/RemoteSensingTeacher#12]
您好 您已经上传了Xview to Dota这一组数据集 请问可以将其他数据集上传吗

**Comment by h751410234** [comment]
试试这个，里面是所有数据集的json。图片就是官方的，我其他没有进行预处理。链接: https://pan.baidu.com/s/1H7NCjZKHET7TvgQglflq5w?pwd=6ix4 提取码: 6ix4

**Comment by G-200010** [comment]
您好 请问可以把不同json对应的train test数据集图片部分一块上传了吗 我看您论文中涉及数据集划分等内容

**Comment by h751410234** [comment]
直接按照论文分了吧，我应该没做别的处理

**Comment by G-200010** [comment]
好的 谢谢
