### ISSUE TITLE
自定义数据集复现

### ISSUE THREAD

**Issue by mebius-coder** [h751410234/RemoteSensingTeacher#13]
想用其它数据集进行论文工作的复现，应该怎样做呢，尤其对于configurations and pre-trained models

**Comment by h751410234** [comment]
configurations基本和官方Deformable DETR参数一致。准备COCO格式的数据集，按照readme要求配置路径即可。pre-trained models就加载resnet的预训练模型即可（应该是自动下载并加载的）。

**Comment by mebius-coder** [comment]
如果是voc数据集需要做格式的转换吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月5日(周四) 下午2:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [h751410234/RemoteSensingTeacher] 自定义数据集复现 (Issue #13)




 
configurations基本和官方Deformable DETR参数一致。准备COCO格式的数据集，按照readme要求配置路径即可。pre-trained models就加载resnet的预训练模型即可（应该是自动下载并加载的）。

**Comment by mebius-coder** [comment]
实验对于机器有什么要求吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月5日(周四) 下午2:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [h751410234/RemoteSensingTeacher] 自定义数据集复现 (Issue #13)




 
configurations基本和官方Deformable DETR参数一致。准备COCO格式的数据集，按照readme要求配置路径即可。pre-trained models就加载resnet的预训练模型即可（应该是自动下载并加载的）。

**Comment by h751410234** [comment]
voc需要转成coco格式，建议48G显存以上把
