### ISSUE TITLE
数据集资源

### ISSUE THREAD

**Issue by mebius-coder** [h751410234/RemoteSensingTeacher#14]
除了xView and DOTA1.0，您是否有其它几个数据集网盘资源呢，如果有感激不尽！

**Comment by h751410234** [comment]
试试这个，里面是所有数据集的json。图片就是官方的，我其他没有进行预处理。链接: https://pan.baidu.com/s/1H7NCjZKHET7TvgQglflq5w?pwd=6ix4 提取码: 6ix4

**Comment by mebius-coder** [comment]
谢谢，还是好人多呀，祝好




夕阳下的浪客
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "h751410234/RemoteSensingTeacher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月6日(星期五) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [h751410234/RemoteSensingTeacher] 数据集资源 (Issue #14)





 
试试这个，里面是所有数据集的json。图片就是官方的，我其他没有进行预处理。链接: https://pan.baidu.com/s/1H7NCjZKHET7TvgQglflq5w?pwd=6ix4 提取码: 6ix4
