### ISSUE TITLE
模型训练到25轮卡住

### ISSUE THREAD

**Issue by mebius-coder** [h751410234/RemoteSensingTeacher#15]
您好我的模型训练到第25轮时卡住：
![image111](https://github.com/user-attachments/assets/a740d9fd-dab6-4a4d-9aaa-1dc4838fe154)

nvidia-smi显示只有一个卡在占用（之前是两个）：
![image222](https://github.com/user-attachments/assets/63c4b950-61d1-47ce-b1cb-cea648807719)
请问您有没有遇到过这种情况，我的配置是3090*2（24G），batch size是2*2per gpu,请问这样是显存爆了吗

**Comment by h751410234** [comment]
感觉很可能是有一个卡的显存爆了

**Comment by h751410234** [comment]
我感觉2张卡很可能训练的精度不太行，可以参考之前的issues
