### ISSUE TITLE
GPU memory issue

### ISSUE THREAD

**Issue by xi666666** [h751410234/RemoteSensingTeacher#16]
Hello, when I reproduce your code during the training process, more and more GPU memory were used, there should be a GPU memory leak, try each epoch after using torch.cuda.empty_cache() effect is not obvious, is there any solution

**Comment by h751410234** [comment]
我也不太清楚是什么原因导致的，48GB显存的情况下应该不会出现问题。

**Comment by xi666666** [comment]
48G显卡测试确实是能坚持一会儿，到接近60个epoch也会几乎炸掉，我是从14G泄露到47.8G

**Comment by G-200010** [comment]
> 48G显卡测试确实是能坚持一会儿，到接近60个epoch也会几乎炸掉，我是从14G泄露到47.8G

您好 请问您找到解决办法了吗 我用48G卡训练59轮末尾有Dataloader signal killed 也不知道为什么
