### ISSUE TITLE
你好，请问训练有什么技巧么？xView2DOTA训练结果达不到63.3

### ISSUE THREAD

**Issue by OrientSama** [h751410234/RemoteSensingTeacher#5]
我目前使用的配置是:
- RTX 3090Ti
- CUDA 12.4
- PyTorch 2.2.2
- Python 3.12.2

按照您README.md里要求更改了`DAOD.py`，使用`python main.py --config_file ./configs/r50_uda_xView2DOTA_b16.yaml`进行训练，最高的结果如下：
```
- best_checkpoint -->  map50:0.4127303022353169 , epoch:40
- best_semi_ema -->  map50:0.42229827088792504 , epoch:51
- best_ema -->  map50:0.4139248084818917 , epoch:40
```
没有达到您所提到的63.3的map50值。
因此我下载了您在README.md里提供的预训练模型，使用相关语句进行推理，结果却不到22
![屏幕截图 2024-06-26 164412](https://github.com/h751410234/RemoteSensingTeacher/assets/81564896/da3c60bc-13e1-471f-aa16-56d0d69d18f4)
所以，想请问一下，是否有什么训练技巧，或者哪里出错了导致这些问题的？
另一个问题就是标签格式是coco官方的格式吗？因为在您代码的注释里提到了
```
# （1）预测结果后处理，得到分类+回归结果,其中box 为中心点+宽高格式（与target保持一致）
```
让我有些怀疑是否是label的原因。
希望您看到时，能帮我解答一下这些疑问。

**Comment by h751410234** [comment]
（1）请问你的batch_size设置是多少。从你的截图来看，指标存在异常。以我的经验batch_size=2，即每个域的图像（batch_size=1），将导致对抗训练无法成功，指标会异常低，请确保batch_size设置为4以上。

**Comment by h751410234** [comment]
（1）请问你的batch_size设置是多少。从你的第一张截图来看，指标存在异常。以我的经验batch_size=2，即每个域的图像（batch_size=1），将导致对抗训练无法成功，指标会异常低，请确保batch_size设置为4以上。
（2）标签是coco数据集格式。从你的第二张截图看来，我感觉可能的原因是我训练的类别排序和你的不一致，即我预测结果的类别标签和你的数据集标注label错位了，你可以检查下每一个类别的具体mAP值，看看是否存在某一个类别mAP为0的情况。

**Comment by OrientSama** [comment]
batch_size是默认设置4
至于您提到的顺序，我仔细对比了一下，发现确实是这样，改完顺序后，重新验证，结果达到了62.7，您的顺序是`['plane', 'storage-tank', 'ship']`,对应label是0 1 2
![image](https://github.com/h751410234/RemoteSensingTeacher/assets/81564896/4b0efbd7-f99d-414d-b27c-d9aa94de6cab)
但是这个顺序应该不影响我重新训练的效果吧？

**Comment by h751410234** [comment]
（1）从评估的结果来看，62.7是符合预期的。制备数据集的略微差异导致结果略有不同。
（2）关于训练精度问题，最高只仅达到了，42显然是不合理的。我猜想可能有以下原因：
1.检查数据集制备，你的源域和目标域数据集标签是否存在错位。类似于评估模型时发生的情况类似。
2.推荐你训练下仅源域的情况，看是指标是否能达到50左右，以确保训练集和测试集均没有问题。
（3）可否方便告知你用了几块卡训练，以我的经验来看不同卡的数量训练结果存在不小的差异，但达到个58以上还是很容易的。

**Comment by h751410234** [comment]
我们的训练集和数据集切片数量如下，供你参考：
DOTA: Number of image slices (800x800), training set: 4805 images, validation set: 1577 images.
xView: Number of image slices (800x800), training set: 1878 images.

**Comment by h751410234** [comment]
（1）从评估的结果来看，62.7是符合预期的。制备数据集的略微差异导致结果略有不同。
（2）关于训练精度问题，最高只仅达到了，42显然是不合理的。我猜想可能有以下原因：
1.检查数据集制备，你的源域和目标域数据集标签是否存在错位。类似于评估模型时发生的情况。
2.推荐你训练下仅源域的情况，看是指标是否能达到50左右，以确保训练集和测试集均没有问题。
（3）可否方便告知你用了几块卡训练，以我的经验来看不同卡的数量训练结果存在不小的差异，但达到个58以上还是很容易的。
（4）我们的数据集切片数量如下，供你参考：
DOTA: Number of image slices (800x800), training set: 4805 images, validation set: 1577 images.
xView: Number of image slices (800x800), training set: 1878 images.

**Comment by OrientSama** [comment]
1. 关于您提到的数据集标签是否错位的问题，我会进行仔细的检查
2. 主要是一个3090ti在训练
3. 关于你提到的在源域训练，我使用Faster RCNN训练mAP50在49.6左右，是否可以说明没有问题？
4. 我的切片整体与你的十分相似，仅相差5个以内：
    dota_trian:4806 dota_val:1580 xView_train:1880

**Comment by h751410234** [comment]
1. 关于你提到的在源域训练，我使用Faster RCNN训练mAP50在49.6左右，感觉数据集应该不存在问题。
2. 关于训练精度问题，最高42，很像配置文件中batch_size=2的情况。我最近尝试的一次实验中，使用单卡batch_size=2的情况下训练，mAP=47.4。
3. 由于之前没有单卡训练过。我最近将设置batch_size=4，然后使用单卡进行训练，看看结果和你的现象是否一致。

**Comment by h751410234** [comment]
1.关于你提到的在源域训练，我使用Faster RCNN训练mAP50在49.6左右，感觉数据集应该不存在问题。
2.关于训练精度问题，最高42，很像配置文件中batch_size=2的情况。我最近尝试的一次实验中，使用单卡batch_size=2的情况下训练，mAP=47.4。
3.由于之前没有单卡训练过。我最近将设置batch_size=4，然后使用单卡进行训练，看看结果和你的现象是否一致。
4.如果你想得到更高的精度，推荐你尝试使用我的新工作：https://github.com/h751410234/DATR，DINO框架下的域适应训练将变得非常稳定。在我的实验中，这个代码可以很容易的得到65以上的mAP，在xView2DOTA任务。使用了2块GPU，每个域的图片batch_size=2。

**Comment by h751410234** [comment]
1.关于你提到的在源域训练，我使用Faster RCNN训练mAP50在49.6左右，感觉数据集应该不存在问题。
2.关于训练精度问题，最高42，很像配置文件中batch_size=2的情况。我最近尝试的一次实验中，使用单卡batch_size=2的情况下训练，mAP=47.4。
3.由于之前没有单卡训练过。我最近将设置batch_size=4，然后使用单卡进行训练，看看结果和你的现象是否一致。
4.如果你想得到更高的精度，推荐你尝试使用我的新工作：https://github.com/h751410234/DATR，DINO框架下的域适应训练将变得非常稳定。在我的实验中，这个代码可以很容易的得到65以上的mAP，在xView2DOTA任务。使用了2块GPU，每个域的图片batch_size=2。

**Comment by h751410234** [comment]
1.关于你提到的在源域训练，我使用Faster RCNN训练mAP50在49.6左右，感觉数据集应该不存在问题。
2.关于训练精度问题，最高42，很像配置文件中batch_size=2的情况。我最近尝试的一次实验中，使用单卡batch_size=2的情况下训练，mAP=47.4。
3.由于之前没有单卡训练过。我最近将设置batch_size=4，然后使用单卡进行训练，看看结果和你的现象是否一致。
4.如果你想得到更高的精度，推荐你尝试使用我的新工作：DATR，DINO框架下的域适应训练将变得非常稳定。在我的实验中，这个代码可以很容易的得到65以上的mAP，在xView2DOTA任务。使用了2块GPU，每个域的图片batch_size=2。

**Comment by G-200010** [comment]
请问可以分享一下你进行dota和xView图像前处理的代码吗 @OrientSama

**Comment by h751410234** [comment]
代码确实不太好找了，我把我处理好的数据集放到百度网盘了，你可以直接下载

**Comment by G-200010** [comment]
我是按照下面图片中的number统计的选择类别后的图像数量 但是数量是1864 不知道问题出在哪里了
<img width="708" alt="问题1" src="https://github.com/h751410234/RemoteSensingTeacher/assets/172945648/4ff68c11-7f9e-4357-9ccc-76778d450d89">
<img width="667" alt="问题2" src="https://github.com/h751410234/RemoteSensingTeacher/assets/172945648/b8a281bf-8818-495c-b39e-69936d8d591f">
<img width="856" alt="问题3" src="https://github.com/h751410234/RemoteSensingTeacher/assets/172945648/5f1703c4-93bb-4a29-ad4e-889811c9a47a">

**Comment by OrientSama** [comment]
> 请问可以分享一下你进行dota和xView图像前处理的代码吗 @OrientSama

我把代码上传到这里了[xView2DOTA_Tools](https://github.com/OrientSama/xView2DOTA_Tools)

**Comment by OrientSama** [comment]
> 1.关于你提到的在源域训练，我使用Faster RCNN训练mAP50在49.6左右，感觉数据集应该不存在问题。 2.关于训练精度问题，最高42，很像配置文件中batch_size=2的情况。我最近尝试的一次实验中，使用单卡batch_size=2的情况下训练，mAP=47.4。 3.由于之前没有单卡训练过。我最近将设置batch_size=4，然后使用单卡进行训练，看看结果和你的现象是否一致。 4.如果你想得到更高的精度，推荐你尝试使用我的新工作：DATR，DINO框架下的域适应训练将变得非常稳定。在我的实验中，这个代码可以很容易的得到65以上的mAP，在xView2DOTA任务。使用了2块GPU，每个域的图片batch_size=2。

调整顺序后有重新训练了一次，截止到现在最高的是 `第54轮，mAP: 46.37` ， 非常感谢你的回复，关于您的新工作，我会抽时间学习一下。

**Comment by h751410234** [comment]
好的，我也将单卡batch_size=4训练一次，看看和你的现象是否一致。

**Comment by G-200010** [comment]
> > 请问可以分享一下你进行dota和xView图像前处理的代码吗 @OrientSama
> 
> 我把代码上传到这里了[xView2DOTA_Tools](https://github.com/OrientSama/xView2DOTA_Tools)

谢谢！

**Comment by G-200010** [comment]
> 1. 关于您提到的数据集标签是否错位的问题，我会进行仔细的检查
> 2. 主要是一个3090ti在训练
> 3. 关于你提到的在源域训练，我使用Faster RCNN训练mAP50在49.6左右，是否可以说明没有问题？
> 4. 我的切片整体与你的十分相似，仅相差5个以内：
>    dota_trian:4806 dota_val:1580 xView_train:1880

您好 请问您用3090ti单卡跑batchsize训练为4时有对代码做什么调整吗 我用3090跑第4轮显存只剩不到1000MB了 并且还有上涨的趋势

**Comment by G-200010** [comment]
> 1. 关于您提到的数据集标签是否错位的问题，我会进行仔细的检查
> 2. 主要是一个3090ti在训练
> 3. 关于你提到的在源域训练，我使用Faster RCNN训练mAP50在49.6左右，是否可以说明没有问题？
> 4. 我的切片整体与你的十分相似，仅相差5个以内：
>    dota_trian:4806 dota_val:1580 xView_train:1880

您好 请问您用3090ti单卡跑batchsize训练为4时有对代码做什么调整吗 我用3090跑第4轮显存只剩不到1000MB了 并且还有上涨的趋势 @OrientSama

**Comment by h751410234** [comment]
（1）

> 我目前使用的配置是:
> 
> * RTX 3090Ti
> * CUDA 12.4
> * PyTorch 2.2.2
> * Python 3.12.2
> 
> 按照您README.md里要求更改了`DAOD.py`，使用`python main.py --config_file ./configs/r50_uda_xView2DOTA_b16.yaml`进行训练，最高的结果如下：
> 
> ```
> - best_checkpoint -->  map50:0.4127303022353169 , epoch:40
> - best_semi_ema -->  map50:0.42229827088792504 , epoch:51
> - best_ema -->  map50:0.4139248084818917 , epoch:40
> ```
> 
> 没有达到您所提到的63.3的map50值。 因此我下载了您在README.md里提供的预训练模型，使用相关语句进行推理，结果却不到22 ![屏幕截图 2024-06-26 164412](https://private-user-images.githubusercontent.com/81564896/343085730-da3c60bc-13e1-471f-aa16-56d0d69d18f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjE3MTgsIm5iZiI6MTcxOTY2MTQxOCwicGF0aCI6Ii84MTU2NDg5Ni8zNDMwODU3MzAtZGEzYzYwYmMtMTNlMS00NzFmLWFhMTYtNTZkMGQ2OWQxOGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDExNDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NzExYzlkN2JmZTQxZDdjMTNmMmRlNWE1Y2RhMGYxZDQyM2Q3NGEyMjkzYjk1MjYxZDgxNDdjZTNjMjk2YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M4wEeeeXGIa5rXSa5-Jgkjj38_fDPtuQBkA6f-h2-iY) 所以，想请问一下，是否有什么训练技巧，或者哪里出错了导致这些问题的？ 另一个问题就是标签格式是coco官方的格式吗？因为在您代码的注释里提到了
> 
> ```
> # （1）预测结果后处理，得到分类+回归结果,其中box 为中心点+宽高格式（与target保持一致）
> ```
> 
> 让我有些怀疑是否是label的原因。 希望您看到时，能帮我解答一下这些疑问。

（1）我尝试使用单卡batchsize设置为4训练，出现了和你类似的现象，mAP50为48左右。我猜想可能和检测器有关，deformable detr可能需要大batch_size才可以练的比较好。推荐使用官方版本的deformable detr训练一下以验证这一个猜想。我们的精度是在4卡，总共batch_size=16的情况下得到的。
（2）如果你想在单卡上得到较高的精度，我推荐你尝试使用我的新工作：DATR，DINO框架下的域适应训练将变得非常稳定。经过我的测试，在xView2DOTA任务中（使用Sim10k to Cityscapes的配置修改class_num即可），使用1块GPU训练mAP50达到了64.4。

**Comment by OrientSama** [comment]
> （1）
> 
> > 我目前使用的配置是:
> > 
> > * RTX 3090Ti
> > * CUDA 12.4
> > * PyTorch 2.2.2
> > * Python 3.12.2
> > 
> > 按照您README.md里要求更改了`DAOD.py`，使用`python main.py --config_file ./configs/r50_uda_xView2DOTA_b16.yaml`进行训练，最高的结果如下：
> > ```
> > - best_checkpoint -->  map50:0.4127303022353169 , epoch:40
> > - best_semi_ema -->  map50:0.42229827088792504 , epoch:51
> > - best_ema -->  map50:0.4139248084818917 , epoch:40
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 没有达到您所提到的63.3的map50值。 因此我下载了您在README.md里提供的预训练模型，使用相关语句进行推理，结果却不到22 ![屏幕截图 2024-06-26 164412](https://private-user-images.githubusercontent.com/81564896/343085730-da3c60bc-13e1-471f-aa16-56d0d69d18f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjE3MTgsIm5iZiI6MTcxOTY2MTQxOCwicGF0aCI6Ii84MTU2NDg5Ni8zNDMwODU3MzAtZGEzYzYwYmMtMTNlMS00NzFmLWFhMTYtNTZkMGQ2OWQxOGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDExNDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NzExYzlkN2JmZTQxZDdjMTNmMmRlNWE1Y2RhMGYxZDQyM2Q3NGEyMjkzYjk1MjYxZDgxNDdjZTNjMjk2YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M4wEeeeXGIa5rXSa5-Jgkjj38_fDPtuQBkA6f-h2-iY) 所以，想请问一下，是否有什么训练技巧，或者哪里出错了导致这些问题的？ 另一个问题就是标签格式是coco官方的格式吗？因为在您代码的注释里提到了
> > ```
> > # （1）预测结果后处理，得到分类+回归结果,其中box 为中心点+宽高格式（与target保持一致）
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 让我有些怀疑是否是label的原因。 希望您看到时，能帮我解答一下这些疑问。
> 
> （1）我尝试使用单卡batchsize设置为4训练，出现了和你类似的现象，mAP50为48左右。我猜想可能和检测器有关，deformable detr可能需要大batch_size才可以练的比较好。推荐使用官方版本的deformable detr训练一下以验证这一个猜想。我们的精度是在4卡，总共batch_size=16的情况下得到的。 （2）如果你想在单卡上得到较高的精度，我推荐你尝试使用我的新工作：DATR，DINO框架下的域适应训练将变得非常稳定。经过我的测试，在xView2DOTA任务中（使用Sim10k to Cityscapes的配置修改class_num即可），使用1块GPU训练mAP50达到了64.4。

非常感谢您的回复，看来确实与batch_size有很大的关系。

**Comment by OrientSama** [comment]
> > 1. 关于您提到的数据集标签是否错位的问题，我会进行仔细的检查
> > 2. 主要是一个3090ti在训练
> > 3. 关于你提到的在源域训练，我使用Faster RCNN训练mAP50在49.6左右，是否可以说明没有问题？
> > 4. 我的切片整体与你的十分相似，仅相差5个以内：
> >    dota_trian:4806 dota_val:1580 xView_train:1880
> 
> 您好 请问您用3090ti单卡跑batchsize训练为4时有对代码做什么调整吗 我用3090跑第4轮显存只剩不到1000MB了 并且还有上涨的趋势 @OrientSama

你好，没有改动。
