### ISSUE TITLE
（1）I have uploaded my prepared dataset to Baidu Netdisk, and you can download it for use.

### ISSUE THREAD

**Issue by ZFU123456** [h751410234/RemoteSensingTeacher#6]
（1）I have uploaded my prepared dataset to Baidu Netdisk, and you can download it for use.
（2）The xView2DOTA model we released is not the EMA model, so it will produce an error. You can use this command for evaluation: python evaluation.py --config_file {CONFIG_FILE} --opts EVAL True RESUME {CHECKPOINT_FILE}

_Originally posted by @h751410234 in https://github.com/h751410234/RemoteSensingTeacher/issues/4#issuecomment-2193385592_

**Comment by ZFU123456** [comment]
您好           （1）I have uploaded my prepared dataset to Baidu Netdisk, and you can download it for use. 您上传的这个数据集能能只能训练模型吗？

**Comment by h751410234** [comment]
没太理解，上传的这个数据集包括训练集和测试集

**Comment by ZFU123456** [comment]
我的意思是 您上传的这个数据集在训练之前是否要做处理？

**Comment by h751410234** [comment]
可以直接用，不需要处理

**Comment by ZFU123456** [comment]
当我把您上传的数据放在了DAOD.py 的路径下，
'xView': {
            'train_img': '/Domain-Adaptive/RemoteSensingTeacher-main/data/xViewDOTA/paperdata/xView/crop_800_100_3c/train_images',
            'train_anno': '/Domain-Adaptive/RemoteSensingTeacher-main/data/xViewDOTA/paperdata/xView/crop_800_100_3c/coco_annotations',
        },
        'DOTA': {
            'train_img': '/Domain-Adaptive/RemoteSensingTeacher-main/data/xViewDOTA/paperdata/DOTA1.0/crop_800_100_3c/train/train_images',
            'train_anno': '/Domain-Adaptive/RemoteSensingTeacher-main/data/xViewDOTA/paperdata/DOTA1.0/crop_800_100_3c/annotations/train_3c.json',
            'val_img': '/Domain-Adaptive/RemoteSensingTeacher-main/data/xViewDOTA/paperdata/DOTA1.0/crop_800_100_3c/val/val_images',
            'val_anno': /Domain-Adaptive/RemoteSensingTeacher-main/data/xViewDOTA/paperdata/DOTA1.0/crop_800_100_3c/annotations/val_3c.json',

但是报错了，错误是： dataset = json.load(open(annotation_file, 'r'))
IsADirectoryError: [Errno 21] Is a directory: 'Domain-Adaptive/RemoteSensingTeacher-main/data/xViewDOTA/paperdata/xView/crop_800_100_3c/coco_annotations'
出现的错误 我怀疑是数据格式不对，是否还需要做下处理呢

**Comment by h751410234** [comment]
这一行写错了，'train_anno': '/Domain-Adaptive/RemoteSensingTeacher-main/data/xViewDOTA/paperdata/xView/crop_800_100_3c/coco_annotations',
},指定到.json文件

**Comment by h751410234** [comment]
可以先看一下报错，看起来是这一行写错了，'train_anno': '/Domain-Adaptive/RemoteSensingTeacher-main/data/xViewDOTA/paperdata/xView/crop_800_100_3c/coco_annotations',
},指定到.json文件

**Comment by ZFU123456** [comment]
感谢感谢 打扰了 是我粗心了
