### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by G-200010** [h751410234/RemoteSensingTeacher#8]
您好 我在训练时将配置文件中numworkers改为了1 LR改为了0.0001 batchsize改为了2 其他都没变 数据集是您上传的数据集 进行了训练 产生如下报错 您知道是怎么回事吗 期待您的回复
![11](https://github.com/h751410234/RemoteSensingTeacher/assets/172945648/72957096-6a61-43e0-bcbe-965ff68379a4)

**Comment by h751410234** [comment]
看起来像配置的类别数没改？和数据集不匹配

**Comment by G-200010** [comment]
您好 请问您说的配置的类别数具体指的是什么呢 我对于config配置文件的内容只进行了问题中的修改 按照readme修改了一些东西 其他内容都没动 数据集用的是您上传的数据集 请问您说的配置的类别数具体指的是什么呢 burn-in阶段的训练没报错 刚刚进入第51轮时报的错

**Comment by h751410234** [comment]
如果您使用的的百度网盘下载的xView和DOTA数据集，然后使用的是xView2DOTA的配置。我也不太清楚报错是什么原因，不过从上面的精度来看0.27的精度看起来非常奇怪，xView2DOTA我这边单卡训练的在加入自训练之前精度40+是有的。

**Comment by h751410234** [comment]
（1）您如果这次训练是xView到DOTA的配置文件，使用的是百度网盘下载的数据集。报错看起来似乎非常奇怪，报错的意思是说你预测的分类结果超过索引了2了，但配置文件的class_num数设置的应该是4，不应该超过索引。具体原因我也看不太出来是因为什么导致。
（2）训练xView到DOTA，上面的精度看起来很奇怪27.5，我这边单卡训练，在自训练之前40+还是有的。

**Comment by h751410234** [comment]
（1）您如果这次训练是xView到DOTA的配置文件，使用的是百度网盘下载的数据集。报错看起来似乎非常奇怪，报错的意思是说你预测的分类结果超过索引了2了，但配置文件的class_num数设置的应该是4，不应该超过索引。具体原因我也看不太出来是因为什么导致。
（2）训练xView到DOTA，上面的精度看起来很奇怪27.5，我这边单卡训练，在自训练之前40+还是有的。
（3）如果配置确实没有问题的话，我猜测可能是burn in阶段训练的检测器精度太差了，导致这张图没有预测到结果，因此产生的bug，你可能需要自己加个判断跳过没有预测结果的情况。

**Comment by h751410234** [comment]
（1）您如果这次训练是xView到DOTA的配置文件，使用的是百度网盘下载的数据集。报错看起来似乎非常奇怪，报错的意思是说你预测的分类结果超过索引了2了，但配置文件的class_num数设置的应该是4，不应该超过索引。具体原因我也看不太出来是因为什么导致。
（2）训练xView到DOTA，上面的精度看起来很奇怪27.5，我这边单卡训练，在自训练之前40+还是有的。
（3）如果配置确实没有问题的话，我猜测可能是burn in阶段训练的检测器精度太差了，导致这张图没有预测到结果，因此产生的bug（我不太确定当前代码是否有这个判断）。如果没有，你可能需要自己加个判断跳过没有预测结果的情况。

**Comment by G-200010** [comment]
您好 是对xView到Dota的训练 27,5的精度是AP 0.5:0.95 AP50的精度是在40+的

**Comment by G-200010** [comment]
您好 是对xView到Dota的训练 27,5的精度是AP 0.5:0.95 AP50的精度是在40+的

**Comment by h751410234** [comment]
对的，单卡在burn in阶段

**Comment by h751410234** [comment]
那应该没啥问题，我没遇到过你那个错误，可能需要你自己debug下看看为什么会超索引

**Comment by h751410234** [comment]
那应该没啥问题，我没遇到过你那个错误，可能需要你自己debug下看看为什么会超索引。具体的看一下，threshold的维度和具体值

**Comment by h751410234** [comment]
那应该没啥问题，我没遇到过你那个错误，可能需要你自己debug下看看为什么会超索引。具体的看一下，threshold的维度和具体值，报错看起来threshold是一个空列表，不太清楚具体原因

**Comment by h751410234** [comment]
那应该没啥问题，我没遇到过你那个错误，可能需要你自己debug下看看为什么会超索引。具体的看一下，threshold的维度和具体值。

**Comment by G-200010** [comment]
好的 感谢您的回答
